### ISSUE TITLE
On Create Account screen, check for nickname existence in DB on blur

### ISSUE THREAD

**Issue by willbach** [blockmason/lndr-mobile#105]
@aupiff will make an endpoint to check if a nickname already exists.

**Comment by aupiff** [comment]
this endpoint is live.

docs: https://github.com/blockmason/lndr/blob/master/lndr-backend/README.md#get-taken_nicknick

**Comment by TheAznShumai** [comment]
https://github.com/blockmason/lndr-mobile/pull/110
