### ISSUE TITLE
Can't search for user name with @ symbol

### ISSUE THREAD

**Issue by johnnyproton** [blockmason/lndr-mobile#112]
When I type in @blockmason the user doesn't show up.  It does show up if I just type blockmason.

**Comment by aupiff** [comment]
Let's have the mobile app remove the leading @ from a search term if present.

**Comment by timgalebach** [comment]
@TheAznShumai : implement this in the new ui port.

**Comment by TheAznShumai** [comment]
PR https://github.com/blockmason/lndr-mobile/pull/131
