### ISSUE TITLE
iphone keyboard popup gets in the way when restoring

### ISSUE THREAD

**Issue by nosequeldeebee** [blockmason/lndr-mobile#121]
on iphone 6s

to reproduce:

- go to "restore" account
- click in mnemonic text field to paste in mnemonic

expected: 

- iphone keyboard pops up but leaves enough room in text field to paste in mnemonic

observed:

- iphone keyboard pops up and hides text field so you cannot paste

![img_1784](https://user-images.githubusercontent.com/15616604/34321592-711525b6-e7c7-11e7-8198-067367281aba.png)

**Comment by willbach** [comment]
#136
