### ISSUE TITLE
Account Shouldn't Lock on Backgrounding

### ISSUE THREAD

**Issue by timgalebach** [blockmason/lndr-mobile#134]
Currently you have to type the password whenever the app is reopened from being put in the background. Should have a time check where this doesn't happen within an hour/day or whatever.

**Comment by willbach** [comment]
#136

**Comment by denizej** [comment]
I think the security level should be partially defined by the user as some may prefer this feature or even something higher level

**Comment by willbach** [comment]
Reopened this to introduce functionality to allow user to customize the lock delay

**Comment by willbach** [comment]
#137
