### ISSUE TITLE
Create and Restore Account

### ISSUE THREAD

**Issue by nestedlook** [blockmason/lndr-mobile#141]
When I click on Create Account or when I click on Restore after keying in the recovery phrase, the UI doesnt have any indication of the APP working in the background. Even shade of the icon didnt change to convey that the user input was accepted. The create account or restore takes about 10-20 seconds and user need to be given some indication of work in progress in the background..or it might lead to anxiuos moments when the app is in real use.

**Comment by willbach** [comment]
Same as #64
