### ISSUE TITLE
Cursor over decimal point when entering amount

### ISSUE THREAD

**Issue by denizej** [blockmason/lndr-mobile#143]
When entering an amount owed the user must tap on the $0.00 field then the cursor is left blinking over the decimal point, and $0.00 is still displayed.
It would possibly be better if the amount field is cleared of the digits and the cursor is left behind the $ so that the user now can clearly tell they are entering an amount

**Comment by denizej** [comment]
Android oneplus 3t

**Comment by willbach** [comment]
#186
