### ISSUE TITLE
Exiting settings screen 

### ISSUE THREAD

**Issue by denizej** [blockmason/lndr-mobile#147]
The current way to exit the settings screen is by the small cancel link/text at the bottom, which is so far down I have to scroll to it.
Rather than "cancel" it should maybe read "return" or "back" otherwise it implies any changes are undone or clipboard cleared.
And the return text/button could be top left or somewhere more visible.
It would be good if the back button worked in this way but that's another issue

**Comment by denizej** [comment]
Android oneplus 3t

**Comment by willbach** [comment]
#138
