### ISSUE TITLE
Scripts for automating building

### ISSUE THREAD

**Issue by mattsmithies** [blockmason/lndr-mobile#15]
Need script for single step building:

**begin_Lndr:**
yarn
react-native link 
yarn run typescript
yarn start

**start_mobile:**
react-native run-ios (new tab)
react-native run-android (new tab)
react-native log-android (new tab)
react-native log-ios (new tab)

optional: 
**install_indr:**
rm -rf node_modules/ && npm install

**Comment by NateFerrero** [comment]
it's LNDR not indr
