### ISSUE TITLE
Stylistic Notes From User Testing

### ISSUE THREAD

**Issue by walkward** [blockmason/lndr-mobile#171]
Great work on this! I really couldn't find any glaring issues, but I'll share a few of my thoughts anyways:

1. One of the first things I noticed was that the app is not "full-bleed" underneath the power/signal/time/toolbar area. The logo and black background should extend to the top of the screen.
2. The "Start New Debt" and "Needs Review" headers are not clearly associated with their corresponding sections. Using a header style similar to "Pending" on the activity page would solve this (screen 2).
3. Poor readability for the light weight font (screen 3).
4. Inconsistent styles for ETH TRANSFER and Friend. The font-size and text-transform styles vary for "ETH TRANSFER" and "Friend" from the main menu (screen 4 & 5).
5. I had an issue scrolling up from the bottom of the settings page. I was not able to reproduce this issue consistently, sorry.
6. There are two different methods being used for closing screens (The upper left "X" and the "Cancel" near the bottom). Having one floating close trigger would be preferred over having one or the other or both. Also, the cancel icon is not consistently red (see settings screen).
7. As a user, I expected some feedback when copying my ETH address to my clipboard. Some sort of toast or tooltip alert saying "Copied" would be great.

Please take these notes with a grain of salt, I really couldn't find any other issues :) Altogether the team killed it!

| | | |
| ------------- |:-------------:| -----:|
| ![img_0037](https://user-images.githubusercontent.com/19615034/35710666-ec90e496-0775-11e8-8a5d-1e0aa8339e48.PNG) | ![img_0047](https://user-images.githubusercontent.com/19615034/35710669-ecedb270-0775-11e8-8553-5bf53d7068f5.jpg) | ![img_0038](https://user-images.githubusercontent.com/19615034/35710667-eca3b80a-0775-11e8-9437-48df75a1d2c0.jpg) |
| ![img_0046](https://user-images.githubusercontent.com/19615034/35710670-ecfe88c0-0775-11e8-84e0-f70eac1c8a8d.jpg) | ![img_0048](https://user-images.githubusercontent.com/19615034/35710668-ecbaa07e-0775-11e8-9e19-57533d45f109.jpg) |  |

**Comment by willbach** [comment]
#188
