### ISSUE TITLE
LNDR ios app testing feedback

### ISSUE THREAD

**Issue by GeorgeLV1** [blockmason/lndr-mobile#176]
1 ) During registration, when I am filling a second form with password confirmation, keyboard is over it. Looks strange if I can't see what I'm typing in there. Need to close the keyboard fully, to see all the forms. (screenshot)
http://i67.tinypic.com/2iu82fb.png
2 ) Users search. As thats a mobile app, I think that would be great if contacts were associated with phonebook contacts. For example, there should be 2 fields: 1 one - global user search 2 - quick and simple search for friends from phone contacts. May be it's good to use mobile number or ios name for correlation with LNDR users.

Overall, it's very good! Is working, and simple. I'd use that in real life with my friends if that's possible. Great idea.

user: catharsus@gmail.com / lndr: yuralv1

**Comment by willbach** [comment]
I will look at 1). As for 2), the problem is that Lndr does not use phone number to associate accounts. We may look at that as a future feature but it is not currently in the roadmap.

**Comment by willbach** [comment]
#186
