### ISSUE TITLE
Usability when settling debt

### ISSUE THREAD

**Issue by sebthecoder** [blockmason/lndr-mobile#178]
There are two ways to pay back my friends:
1. Pay ETH in the Lndr app
2. I pay offline and the transaction is recorded in the Lndr app
For me as the borrower, I am paying back my debt in both situations.
In the Lndr app the system for methods 1. and 2. are completely different, which I see as a usability problem. If I pay off debt offline, I must enter the payment not as a repayment of debt, but as a new loan to my friend. If I pay via ETH, I hit the Settle button, and do not create a new loan to my friend.
I would prefer to see more consistency, e.g. If I hit the "Settle" button to choose between offline payment or ETH.

**Comment by aupiff** [comment]
The mechanism for settling debts is to issue a new loan via the CreditProtocol smart contract. The only difference on the backend between ETH settlement and offline settlement is that the server can wait until it sees a valid ETH transfer to submit a settlement loan to the CreditProtocol smart contract.

**Comment by willbach** [comment]
Closing this because we are not adding an offline settlement feature. Users can record a non-Eth / non-Lndr settlement as a new transaction
