### ISSUE TITLE
Use `lndr-server`'s /config endpoint for gasPrice & exchange rates

### ISSUE THREAD

**Issue by aupiff** [blockmason/lndr-mobile#196]
- eth gasstation might go down
- can't control response times for EGS and coinbase
- reduce number of necessary requests to 1
- reduce the amount of hardcoded urls in case 3rd party resources change
- we might not be displaying accurate data about settlement cost if there's mismatch between our values for the exchange rate

**Comment by willbach** [comment]
#197
