### ISSUE TITLE
Auto-add non-friends whose debts I confirm to my friend list

### ISSUE THREAD

**Issue by timgalebach** [blockmason/lndr-mobile#31]
This is probably OK, with spam protection, but at least if I confirm it, that person should be added as one of my friends automatically.

**Comment by timgalebach** [comment]
Switching this to alpha because the use case has arisen so frequently in initial testing.

**Comment by willbach** [comment]
This should go in the lndr repo for the backend. As per @aupiff, this functionality should be added to the file /lndr/lndr-backend/src/Lndr/Handler/Credit.hs just before line 122
