### ISSUE TITLE
Autocomplete friend nicknames

### ISSUE THREAD

**Issue by timgalebach** [blockmason/lndr-mobile#33]
Friend nicknames should auto-complete when searching, maybe past a certain number of characters.

**Comment by aupiff** [comment]
I'll have to make changes to both mobile app and backend to make this work. I'll use postgres fuzzy search for this.

**Comment by mattsmithies** [comment]
The code changes on mobile to make this happen will be relatively trivial, although it would be advisable to return a limited amount of users.

**Comment by aupiff** [comment]
this is already live.
