### ISSUE TITLE
default behavior when selecting a friend

### ISSUE THREAD

**Issue by aupiff** [blockmason/lndr-mobile#42]
<img width="386" alt="screen shot 2017-11-22 at 10 09 03" src="https://user-images.githubusercontent.com/804266/33134261-3d414c0a-cf6d-11e7-9f03-8502276ed04e.png">

The default behavior when clicking on a friend should not be removal. A removal button can appear, but it should be small.

We should display a personal balance here and not on the main page. It is very computationally intensive to compute two-party balances, it'd be good if we limited their calculation to this page.

**Comment by mattsmithies** [comment]
Offsetting the expensive functions to this is definitely preferred.

**Comment by aupiff** [comment]
Friend info box now does not assume you want to delete your friend. Additionally, two-party balance is displayed. There is still a big remove button, but that's alright for now.
