### ISSUE TITLE
Home screen should not show two-party balances, but recent tx activity

### ISSUE THREAD

**Issue by aupiff** [blockmason/lndr-mobile#43]
We should show recently approved transactions on the main page and rename the activity page "Pending". All the two party balances should only be discoverable in the friends tab.

**Comment by mattsmithies** [comment]
Agreed, so the activity/pending tab will only show pending as a single list, no extra tab cheaper and nicer to the server + JS thread.

**Comment by aupiff** [comment]
Yeah, and the tabs within tabs was weird.

**Comment by aupiff** [comment]
done.
