### ISSUE TITLE
figure out cause of unmounted component warning

### ISSUE THREAD

**Issue by aupiff** [blockmason/lndr-mobile#44]
<img width="376" alt="screen shot 2017-11-22 at 10 49 07" src="https://user-images.githubusercontent.com/804266/33136292-dc811534-cf72-11e7-911c-5fd0c1281152.png">

Let's get a link to the line causing this error and then let's fix it.

**Comment by mattsmithies** [comment]
That is when a previous tab list is trying to render after network calls for GET requests and you have switched tabs or are viewing a dialog.

**Comment by mattsmithies** [comment]
Briefly for clarity this is resolved by having a mutable 'still relevant' boolean flag in a given component. When a component unmounts, set the 'relevant' flag to false which stops setState from being called. See Pending and recent for the activity sub-tabs as an example. 

`this.stillRelevant && this.setState({ pendingTransactionsLoaded: true, pendingTransactions })`

**Comment by willbach** [comment]
Closing as it is no longer occurring after #135
