### ISSUE TITLE
Top right "+" menu covers underlying elements

### ISSUE THREAD

**Issue by timgalebach** [blockmason/lndr-mobile#49]
The underlying screen should probably get fuzzed/layered out when that top "+" is clicked, to make the UI look right.
<img width="363" alt="screen shot 2017-11-23 at 8 36 31 pm" src="https://user-images.githubusercontent.com/2196339/33192100-0806d6d2-d08e-11e7-9a8b-2940dd59eb0c.png">

**Comment by timgalebach** [comment]
Also the "+" button should be slightly smaller.

**Comment by aupiff** [comment]
fixed (primitive fix on Android, better fix coming in beta.)
