### ISSUE TITLE
use lndr/user/minimumNicknameLength var in nick creation

### ISSUE THREAD

**Issue by aupiff** [blockmason/lndr-mobile#78]
In what is currently an open PR, we're using a magic number to test valid nickname length.

In another PR, I created a var called `minimumNicknameLength` that should be used in place of that magic number.

**Comment by TheAznShumai** [comment]
https://github.com/blockmason/lndr-mobile/pull/98

**Comment by aupiff** [comment]
merged. thanks @TheAznShumai
