### ISSUE TITLE
Screen doesn’t adjust to display (android)

### ISSUE THREAD

**Issue by thenameisdarryl** [blockmason/lndr-mobile#82]

**Comment by TheAznShumai** [comment]
Not sure what this means.  Can you include step to reproduce and/or screenshots?

**Comment by thenameisdarryl** [comment]
![lndr](https://user-images.githubusercontent.com/34250344/33993904-c1c59af4-e0d8-11e7-9bc8-7228995792ff.jpg)
The "Next" Button

**Comment by willbach** [comment]
#136
