### ISSUE TITLE
Landscape mode login screen doesn’t scroll unable to fill in password

### ISSUE THREAD

**Issue by thenameisdarryl** [blockmason/lndr-mobile#84]

**Comment by willbach** [comment]
unable to replicate this on emulators, what device was used when this issue occurred?

**Comment by thenameisdarryl** [comment]
Old android phone 
Type: LG-H320
Android: 5.0.1

**Comment by willbach** [comment]
PR #86 should have fixed this. Tested on Android 5.1 emulator and I was able to scroll down in landscape mode.
