### ISSUE TITLE
Decimal jumps amount new debt (android)

### ISSUE THREAD

**Issue by thenameisdarryl** [blockmason/lndr-mobile#90]
Looks like the decimal jumps in the amount field (create new debt) filling in $100 fast becomes 1,000,100

**Comment by thenameisdarryl** [comment]
After deleting the wrong amount it is possible to fill in the right amount fast typing

**Comment by thenameisdarryl** [comment]
![lndrdecimal](https://user-images.githubusercontent.com/34250344/33994777-20eceb38-e0dc-11e7-9ebd-f04a5b83bda0.jpg)

**Comment by timgalebach** [comment]
Input of debt is getting fixed in new UI version.
